#!/usr/bin/env bash
#
# aliasrc
#
# Contains helpful aliases.

# Use neovim instead of vim if it is installed
if command -v nvim &> /dev/null; then
    alias vim="nvim"
fi

# Use exa instead of ls if it is installed
if command -v exa &> /dev/null; then
    alias ls="exa --long --icons --all --group-directories-first --sort name --bytes --header"
fi
