#!/usr/bin/env sh

# This file is the primary configuration file for yabai. All of the main 
# window manager settings are put here.

# Tiling settings
yabai -m config layout              bsp
yabai -m config window_placement    second_child

# Padding/Gap settings
yabai -m config top_padding     10
yabai -m config bottom_padding  10
yabai -m config left_padding    10
yabai -m config right_padding   10
yabai -m config window_gap      10

# Split ratio settings
yabai -m config auto_balance    off
yabai -m config split_ratio     0.5

# Mouse settings
yabai -m config mouse_modifier          alt
yabai -m config mouse_action1           move
yabai -m config mouse_action2           resize
yabai -m config focus_follows_mouse     off
yabai -m config mouse_follows_focus     on
yabai -m config mouse_drop_action       swap
